import Head from "next/head";
import styles from "@web/styles/Home.module.css";
import { useEffect } from "react";

const ticket =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2N1ZnJlZWxhbmNlLnRlY2giLCJleHAiOjE2Nzk5MDI3MzgsImlhdCI6MTY3OTg2NjczOCwidXNlcl9pZCI6IjU0NmJjMzA3LWVjNjUtNDdhYS1iMDRiLTM2ZjRhYzdlMGQ1NSIsImF1dGhfc2Vzc2lvbl9pZCI6IjYzYjhiMGM2LTY4ZDgtNDEyMi1hY2U4LTdmMzU3MzYxOGIyNiJ9.T3Pdv7MUCdTASeHbtVaU7_KEfJ8e1FiTOwMpqQty_To";

export default function Home() {
  useEffect(() => {
    const conn = new WebSocket(
      `ws://localhost:3030/v1/ws/chat?ticket=${ticket}`
    );

    conn.onopen = (event) => {
      console.log("WebSocket connection opened");
      // send a message to the server
      conn.send("Hello, server!");
    };

    conn.onmessage = (event) => {
      console.log(`Received message from server: ${event.data}`);
    };

    conn.onclose = (event) => {
      console.log(`WebSocket connection closed: ${event.code} ${event.reason}`);
    };

    conn.onerror = (event) => {
      console.error(`WebSocket error: ${event}`);
    };
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleClick}></button>
      </main>
    </>
  );
}
const handleClick = () => {
  // conn.send("Hello World");
};
